[project]
name = "username-checker-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "fastapi>=0.118.2",
    "httpx>=0.28.1",
    "uvicorn>=0.37.0",
]
